# Generated by Django 4.1 on 2024-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_name', models.CharField(max_length=255)),
                ('aliases', models.TextField()),
                ('discovery_date', models.DateField()),
                ('origin', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('risk_assessment', models.CharField(max_length=255)),
                ('minimum_engine', models.CharField(max_length=255)),
                ('minimum_dat', models.CharField(max_length=255)),
                ('dat_release_date', models.DateField()),
                ('virus_characteristics', models.TextField()),
                ('symptoms', models.TextField()),
                ('method_of_infection', models.TextField()),
                ('removal_instructions', models.TextField()),
            ],
        ),
    ]
